### ISSUE TITLE
Nukkit.ru

### ISSUE THREAD

**Issue by M4Gn1T** [EconomyS/EconomyAPI#2]
Could you please upload Economy API, Economy Shop, Economy Sell to nukkit.ru?

**Comment by onebone** [comment]
Sorry for delayed response.

I am now a high school student so I have less time than I had before. I will upload the plugin as soon as it is available, and maybe it will be this Friday to Sunday. (GMT +9, Asia/Seoul)

Thanks!

**Comment by Pub4Game** [comment]
@onebone Thanks!

**Comment by XDqrkneZ** [comment]
Seoul :00
