### ISSUE TITLE
It's more EconomyS plugin?

### ISSUE THREAD

**Issue by tamaskis99** [EconomyS/EconomyAPI#6]
More economy plugins (land, property, etc) making this?

**Comment by onebone** [comment]
Currently I have no plan to create other plugins since I have not enough time. I will make another if I have time, but I don't think that will happen. :(

**Comment by tamaskis99** [comment]
ohh :/ ehm, 1 questions for you... You have contact me on Facebook? My private FB profil: fb.com/kis.j.tamas.5
I want quest you 1-2 "items".
Please, thanks.

**Comment by onebone** [comment]
Unfortunately, I don't have facebook account.
